let assets = [
{id: 2, name: "USD/JPY"},
{id: 35, name: "AUD/USD"},
{id: 38, name: "USD/ILS"},
{id: 39, name: "GOLD"},
{id: 40, name: "EUR/ILS"},
{id: 41, name: "SILVER"},
{id: 42, name: "PLATINUM-JAN17"},
{id: 44, name: "USD/TRY"},
{id: 45, name: "USD/CAD"},
{id: 46, name: "EUR/JPY"},
{id: 47, name: "Former OMANIRIAL"},
{id: 49, name: "Former EU OIL "},
{id: 50, name: "Former MSM"},
{id: 51, name: "TADAWUL"},
{id: 52, name: "Former EGX 30 "},
{id: 53, name: "Former QSI"},
{id: 54, name: "DUBAI"},
{id: 55, name: "Former BLOM "},
{id: 56, name: "KUWAIT "},
{id: 57, name: "Former ZAIN"},
{id: 58, name: "MICEX"},
{id: 59, name: "Former RTS"},
{id: 61, name: "Former USD/EGP"},
{id: 64, name: "USD/RUB"},
{id: 66, name: "NASDAQ"},
{id: 67, name: "BOMBAY SE  "},
{id: 68, name: "former ISE 30/1 "},
{id: 69, name: "EUR/GBP"},
{id: 85, name: "SUGAR (11)-OCT17 "},
{id: 86, name: "S&amp;P 500 "},
{id: 87, name: "DAX"},
{id: 88, name: "CAC 40"},
{id: 89, name: "FTSE 100"},
{id: 90, name: "Former COTTON (2)"},
{id: 91, name: "EUR/USD"},
{id: 93, name: "Former CITI"},
{id: 94, name: "GAZPROM"},
{id: 95, name: "GBP/USD"},
{id: 98, name: "DOW"},
{id: 102, name: "Former Microsoft"},
{id: 103, name: "Former NIKE"},
{id: 104, name: "APPLE"},
{id: 105, name: "ALPHABET Inc C (Google)"},
{id: 106, name: "COCA COLA"},
{id: 107, name: "SBERBANK"},
{id: 108, name: "WHEAT-DEC16"},
{id: 111, name: "HANG SENG"},
{id: 112, name: "SSE180"},
{id: 113, name: "former USD/BRL"},
{id: 114, name: "Former Lukoil"},
{id: 115, name: "BP"},
{id: 116, name: "OIL-JUN17(WTI CRUDE)"},
{id: 117, name: "HSBC HOLDINGS"},
{id: 118, name: "Former Rolce Royce"},
{id: 119, name: "Former BAE SYSTEMS"},
{id: 120, name: "NASDAQ F-JUN17"},
{id: 121, name: "Former S&amp;P FUTURE"},
{id: 122, name: "GBP/RUB"},
{id: 124, name: "Former USDIRS 3 YEARS"},
{id: 125, name: "Former TURKCELL"},
{id: 126, name: "NIKKEI 225 "},
{id: 128, name: "Former TURKCELL (US)"},
{id: 129, name: "Fomer REUTERS"},
{id: 130, name: "CORN-DEC16"},
{id: 132, name: "deleted asset"},
{id: 133, name: "Former Test"},
{id: 134, name: "TATA MOTORS"},
{id: 135, name: "KL FUTURE"},
{id: 136, name: "STRAITS TIMES"},
{id: 137, name: "USD/ZAR"},
{id: 138, name: "Former KLSE INDEX"},
{id: 139, name: "NZD/USD"},
{id: 140, name: "Former CHF"},
{id: 141, name: "ISE 100"},
{id: 142, name: "Former INFOSYS TECH"},
{id: 143, name: "S.BANK INDIA"},
{id: 145, name: "ASX"},
{id: 146, name: "Former Cisco"},
{id: 147, name: "former TOYOTA US"},
{id: 148, name: "EXXON MOBIL"},
{id: 149, name: "BAIDU"},
{id: 150, name: "Former MBW"},
{id: 151, name: "USD/SGD"},
{id: 152, name: "TEVA.TA"},
{id: 153, name: "TEL AVIV 35"},
{id: 154, name: "Former EURILS"},
{id: 155, name: "Former USD/PLN"},
{id: 156, name: "MYLAN U.S."},
{id: 157, name: "USD/CHF"},
{id: 158, name: "nameCOFFEE-SEP17"},
{id: 160, name: "BARCLAYS"},
{id: 161, name: "BNP PARIBAS"},
{id: 162, name: "Former YAHOO"},
{id: 163, name: "EUR/GBP S"},
{id: 164, name: "EUR/USD FUTURE"},
{id: 165, name: "CHINA A50 F-MAR17"},
{id: 166, name: "Former VOLKSWAGEN"},
{id: 167, name: "TOTAL "},
{id: 168, name: "Former 3M"},
{id: 169, name: "Former AIG"},
{id: 170, name: "ALCOA"},
{id: 171, name: "AMAZON"},
{id: 172, name: "Former BAC"},
{id: 173, name: "former BOEING"},
{id: 174, name: "Former CISCO-L"},
{id: 175, name: "Former Citi"},
{id: 176, name: "DELL"},
{id: 177, name: "DISNEY"},
{id: 178, name: "former EBAY"},
{id: 179, name: "FIAT"},
{id: 180, name: "ORANGE S.A."},
{id: 181, name: "former GENERAL ELECTRIC"},
{id: 182, name: "GOLDMAN SACHS"},
{id: 183, name: "Former HEWLETT PACKARD"},
{id: 184, name: "IBM"},
{id: 185, name: "INTEL"},
{id: 186, name: "Former JNJ"},
{id: 187, name: "JP MORGAN CHASE"},
{id: 188, name: "Former McDONALDS"},
{id: 189, name: "Former MICROSOFT"},
{id: 190, name: "former PETROCHINA"},
{id: 191, name: "PETROBRAS"},
{id: 192, name: "PFIZER"},
{id: 193, name: "Former PROCTOR AND GAMBLE"},
{id: 194, name: "RIO TINTO"},
{id: 195, name: "former SONY"},
{id: 196, name: "TESCO"},
{id: 197, name: "former-UBS"},
{id: 198, name: "VODAFONE"},
{id: 199, name: "former WAL-MART"},
{id: 200, name: "DEUTSCHE TELEKOM"},
{id: 201, name: "TOPIX 100"},
{id: 202, name: "POALIM.TA"},
{id: 203, name: "LEUMI"},
{id: 204, name: "ICL.TA"},
{id: 205, name: "AFRICA.TA"},
{id: 206, name: "RATZIO"},
{id: 207, name: "Former unknown"},
{id: 208, name: "Former CELCOM.TA"},
{id: 209, name: "DELEK GROUP"},
{id: 210, name: "Former TEL BANK"},
{id: 211, name: "TA25 FUTURE"},
{id: 212, name: "deleteme"},
{id: 213, name: "USD/VEF"},
{id: 214, name: "test__"},
{id: 215, name: "BOVESPA F-DEC16"},
{id: 216, name: "IBEX"},
{id: 217, name: "Former GSK"},
{id: 218, name: "SAB MILLER"},
{id: 219, name: "UNILEVER"},
{id: 220, name: "BRITISH AMERICAN T"},
{id: 221, name: "NIFTY"},
{id: 222, name: "TOYOTA MOTORS"},
{id: 223, name: "NISSAN MOTOR"},
{id: 224, name: "HITACHI CORP"},
{id: 225, name: "TOSHIBA CO"},
{id: 226, name: "EUR/RUB"},
{id: 227, name: "LOUIS VUITTON"},
{id: 228, name: "VIVENDI "},
{id: 229, name: "DANONE "},
{id: 230, name: "PUBLICIS GROUP"},
{id: 231, name: "FORMER LeverateTest"},
{id: 232, name: "TA25 CALL"},
{id: 233, name: "TA25 PUT"},
{id: 234, name: "former TA 25"},
{id: 235, name: "LUKOIL RS"},
{id: 236, name: "GALOM"},
{id: 237, name: "BHP BILLITON"},
{id: 238, name: "CATERPILLAR"},
{id: 239, name: "former TURKCELL.TU"},
{id: 240, name: "BANCO SANTANDER"},
{id: 241, name: "TELEFONICA"},
{id: 242, name: "former MSM 30"},
{id: 243, name: "ISTANBUL BANK"},
{id: 244, name: "JAKARTA SE"},
{id: 245, name: "TEST-245 - BTC-GBP"},
{id: 246, name: "BANK OF AMERICA"},
{id: 247, name: "CITIGROUP"},
{id: 248, name: "MACQUARIE GROUP"},
{id: 249, name: "AIG"},
{id: 250, name: "ROLLS ROYCE"},
{id: 251, name: "YAHOO"},
{id: 252, name: "ALPHA BANK"},
{id: 253, name: "COCA COLA.AT"},
{id: 254, name: "former NIKE "},
{id: 255, name: "Former MICROSOFT"},
{id: 256, name: "former MICROSOFT"},
{id: 257, name: "test1234"},
{id: 258, name: "former McDONALDS"},
{id: 259, name: "GBP/JPY"},
{id: 260, name: "former BEZEQ"},
{id: 261, name: "CAC 40 F-SEP17"},
{id: 262, name: "DAX F-JUN17"},
{id: 263, name: "S&amp;P F-SEP16"},
{id: 264, name: "EUR/TRY"},
{id: 265, name: "USD/HKD"},
{id: 266, name: "GOLD/ILS"},
{id: 267, name: "NETFLIX"},
{id: 268, name: "Former GBP/JPY"},
{id: 269, name: "former GBP/CHF"},
{id: 270, name: "GBP/CHF"},
{id: 271, name: "McDONALD'S"},
{id: 272, name: "LINKEDIN"},
{id: 273, name: "RTS "},
{id: 274, name: "former USD/PLN"},
{id: 275, name: "former EUR/PLN"},
{id: 276, name: "former EUR/CHF"},
{id: 277, name: "AUD/CHF"},
{id: 278, name: "EUR/CAD"},
{id: 279, name: "EUR/INR"},
{id: 280, name: "USD/INR"},
{id: 281, name: "former gbp/inr"},
{id: 282, name: "GOLD/JPY"},
{id: 283, name: "AUD/JPY"},
{id: 284, name: "CAD/JPY"},
{id: 285, name: "EUR/JPY test"},
{id: 286, name: "RTS F-APR17"},
{id: 287, name: "foremr USDINDEX"},
{id: 288, name: "ANZ BANK"},
{id: 289, name: "AUD/NZD"},
{id: 290, name: "BHP-AU"},
{id: 291, name: "RIO-AU"},
{id: 292, name: "FTSE F-SEP17"},
{id: 293, name: "COSTCO "},
{id: 294, name: "WESTPAC "},
{id: 295, name: "LAS VEGAS SANDS"},
{id: 296, name: "WYNN RESORTS"},
{id: 297, name: "former MGM"},
{id: 298, name: "Natural Gas"},
{id: 299, name: "EBAY"},
{id: 300, name: "SONY"},
{id: 301, name: "BEZEQ"},
{id: 302, name: "BOEING"},
{id: 303, name: "WAL-MART"},
{id: 304, name: "GOLD/EUR"},
{id: 305, name: "FORMER GOLDEUR"},
{id: 306, name: "ASX F-MAR17"},
{id: 307, name: "SAUDI REFINERIES"},
{id: 308, name: "ARABIAN PIPES COMP"},
{id: 309, name: "NIFTY F-SEP17"},
{id: 310, name: "former BSE"},
{id: 311, name: "SAP"},
{id: 312, name: "SMI"},
{id: 313, name: "VOLVO"},
{id: 314, name: "EUR/AUD"},
{id: 315, name: "GBP/CAD"},
{id: 316, name: "CAD/CHF"},
{id: 317, name: "FAZ-SHORT BANKS"},
{id: 318, name: "MICROSOFT"},
{id: 319, name: "GENERAL MOTORS"},
{id: 320, name: "former-TVIX"},
{id: 321, name: "GROUPON"},
{id: 322, name: "former ISE 30"},
{id: 323, name: "F5 NETWORKS"},
{id: 324, name: "MASTERCARD"},
{id: 325, name: "SEARS HOLDINGS"},
{id: 326, name: "FREEPORT McMORAN"},
{id: 327, name: "TNA-LONG X3"},
{id: 328, name: "TZA-SHORT X3"},
{id: 329, name: "SALESFORCE.COM"},
{id: 330, name: "former ALPHA NATURAL R."},
{id: 331, name: "STARBUCKS"},
{id: 332, name: "GOLD/TRY"},
{id: 333, name: "CHF/JPY"},
{id: 334, name: "NZD/JPY"},
{id: 335, name: "USD/UAH"},
{id: 336, name: "IBEX F-SEP17"},
{id: 337, name: "AXIS BANK"},
{id: 338, name: "NIPPON STEEL"},
{id: 339, name: "former RELIANCE"},
{id: 340, name: "TATA STEEL"},
{id: 341, name: "AL RAJHI BANK"},
{id: 342, name: "USD/HUF"},
{id: 343, name: "TEL AVIV VS FTSE"},
{id: 344, name: "BNP PARIBAS VS BARCLAYS"},
{id: 345, name: "former AMAZON VS APPLE"},
{id: 346, name: "APPLE VS ALPHABET"},
{id: 347, name: "GOLD VS SILVER"},
{id: 348, name: "CITIGROUP VS JP MORGAN CHASE"},
{id: 349, name: "former GOLD VS OIL"},
{id: 350, name: "DAX VS FRANCE 40"},
{id: 351, name: "USDLTL"},
{id: 352, name: "ROSNEFT'"},
{id: 353, name: "PSI 20"},
{id: 354, name: "AUD/CAD"},
{id: 355, name: "EUR/NZD"},
{id: 356, name: "GBP/AUD"},
{id: 357, name: "NZD/CHF"},
{id: 358, name: "GBP/NZD"},
{id: 359, name: "EUR/NOK"},
{id: 360, name: "EUR/SEK"},
{id: 361, name: "NZD/CAD"},
{id: 362, name: "former USD/DKK"},
{id: 363, name: "USD/NOK"},
{id: 364, name: "USD/SEK"},
{id: 365, name: "FACEBOOK "},
{id: 366, name: "USD/CNY"},
{id: 367, name: "ALLIANZ SE"},
{id: 368, name: "BAYER AG"},
{id: 369, name: "DAIMLER AG"},
{id: 370, name: "DEUTSCHE BANK AG"},
{id: 371, name: "E.ON AG"},
{id: 372, name: "METRO AG"},
{id: 373, name: "SIEMENS AG"},
{id: 374, name: "VOLKSWAGEN"},
{id: 375, name: "BASF AG"},
{id: 376, name: "KOSPI"},
{id: 377, name: "MOBILE TELESYSTEMS"},
{id: 378, name: "former MECHEL OAO"},
{id: 379, name: "VIMPELCOM"},
{id: 380, name: "RUSSIA MARKET"},
{id: 381, name: "YANDEX N.V"},
{id: 382, name: "former CTC MEDIA"},
{id: 383, name: "RIO T. VS BHP B."},
{id: 384, name: "former McDONALD'S VS STARBUCKS"},
{id: 385, name: "CITIGROUP VS AIG"},
{id: 386, name: "former LINKEDIN VS FACEBOOK"},
{id: 387, name: "former GOOGLE VS BIDU"},
{id: 388, name: "APPLE VS AMAZON"},
{id: 389, name: "NASDAQ VS APPLE"},
{id: 390, name: "FORMER LYNAS CORPORATION"},
{id: 391, name: "NEWCREST MINING"},
{id: 392, name: "ORIGIN ENERGY"},
{id: 393, name: "PALADIN ENERGY"},
{id: 394, name: "WOODSIDE PETROLEUM"},
{id: 395, name: "WOOLWORTHS "},
{id: 396, name: "SAUDI BASIC INDS"},
{id: 397, name: "SAUDI INTG TELECOM"},
{id: 398, name: "CK HUTCHISON"},
{id: 399, name: "BANK OF CHINA"},
{id: 400, name: "CHINA TELECOM"},
{id: 401, name: "CNOOC"},
{id: 402, name: "GOME"},
{id: 403, name: "ICBC BANK"},
{id: 404, name: "AGRI' BANK OF CHINA"},
{id: 405, name: "CHINA LIFE INSURANCE"},
{id: 406, name: "SAMSUNG-KR"},
{id: 407, name: "former BRL"},
{id: 408, name: "PETRO.BR"},
{id: 409, name: "VALE.BSP"},
{id: 410, name: "LeverateTest"},
{id: 411, name: "MANCHESTER UNITED"},
{id: 412, name: "USD/BRL"},
{id: 413, name: "USD/DKK"},
{id: 414, name: "EUR/DKK"},
{id: 415, name: "NORDEA BANK "},
{id: 416, name: "NOVO NORDISK "},
{id: 417, name: "CARLSBERG B"},
{id: 418, name: "DANSKE BANK "},
{id: 419, name: "COLOPLAST "},
{id: 420, name: "MOELLER MAERSK B "},
{id: 421, name: "OMX NORDIC 40  "},
{id: 422, name: "ING GROEP"},
{id: 423, name: "RENAULT"},
{id: 424, name: "BMW"},
{id: 425, name: "OMX C20"},
{id: 426, name: "CHINA MOBILE"},
{id: 427, name: "HSBC-HK"},
{id: 428, name: "HANG SENG F-AUG17"},
{id: 429, name: "AMANA (SE)"},
{id: 430, name: "KEC (SA)"},
{id: 431, name: "SAUDI FISHERIES "},
{id: 432, name: "SHARQIYA DEV"},
{id: 433, name: "PETROCHINA-SHG"},
{id: 434, name: "NIKE"},
{id: 435, name: "Saudi Vitrified Clay Pipe"},
{id: 436, name: "Southern Province Cement"},
{id: 437, name: "United Electronics Company"},
{id: 438, name: "Mouwasat Medical Services Company"},
{id: 439, name: "COMMONWEALTH BANK"},
{id: 440, name: "NIKKEI F-JUN16"},
{id: 441, name: "BLACKBERRY"},
{id: 442, name: "former AT&amp;T"},
{id: 443, name: "QATAR"},
{id: 444, name: "3M"},
{id: 445, name: "CSI 300 "},
{id: 446, name: "former ENZHEN SME COMP"},
{id: 447, name: "TSX 60"},
{id: 448, name: "NATIONAL AUSTRALIA BANK"},
{id: 449, name: "FORTESCUE METALS"},
{id: 450, name: "former IMKB 30"},
{id: 451, name: "TAIEX"},
{id: 452, name: "SHANGHAI COMPOSITE"},
{id: 453, name: "DOLLAR INDEX-APR17"},
{id: 454, name: "VIX "},
{id: 455, name: "SARUSD"},
{id: 456, name: "EUR/CHF"},
{id: 457, name: "USD/MXN"},
{id: 458, name: "BitCOIN/USD"},
{id: 459, name: "BitCoin"},
{id: 460, name: "BitCoin"},
{id: 461, name: "TENCENT HOLDINGS"},
{id: 462, name: "USD/PLN"},
{id: 463, name: "ALPHABET vs FACEBOOK"},
{id: 464, name: "EURO STOXX 50"},
{id: 465, name: "EURO STOXX 50 F-DEC16"},
{id: 466, name: "STOXX 50 F VS FTSE F"},
{id: 467, name: "S&amp;P 500 F VS NASDAQ F"},
{id: 468, name: "CRB INDEX"},
{id: 469, name: "BANK NIFTY"},
{id: 470, name: "INFOSYS(Bombay SE)"},
{id: 471, name: "former ALJAZEERA"},
{id: 472, name: "U.S 10 YEAR-JUN16"},
{id: 473, name: "U.S 30 YEAR-JUN16"},
{id: 474, name: "GERMANY 10YR-MAR17"},
{id: 475, name: "LINKEDIN VS FACEBOOK"},
{id: 476, name: "ROYAL MAIL"},
{id: 477, name: "FTSE MIB F-JUN17"},
{id: 478, name: "TWITTER"},
{id: 479, name: "BitCOIN/USD"},
{id: 480, name: "BitCOIN/EUR"},
{id: 481, name: "FTSE F VS CAC F"},
{id: 482, name: "SANOFI SA"},
{id: 483, name: "AXA SA"},
{id: 484, name: "GOLD VS SILVER"},
{id: 485, name: "BMW VS DAIMLER"},
{id: 486, name: "BMW VS RENAULT"},
{id: 487, name: "VODAFONE VS ORANGE"},
{id: 488, name: "AMAZON VS EBAY"},
{id: 489, name: "ALPHABET VS BAIDU"},
{id: 490, name: "FACEBOOK VS TWITTER"},
{id: 491, name: "LINKEDIN VS TWITTER"},
{id: 492, name: "SSE180 VS CSI300"},
{id: 493, name: "RIO-AU VS BHP-AU"},
{id: 494, name: "McDONALD'S VS STARBUCKS"},
{id: 495, name: "AMAZON VS NETFLIX"},
{id: 496, name: "APPLE VS AMAZON"},
{id: 497, name: "GOLD VS OIL"},
{id: 498, name: "DOW F-JUN17"},
{id: 499, name: "EUR/USD REUTERS "},
{id: 500, name: "LEVTST"},
{id: 501, name: "LLOYDS BANK"},
{id: 502, name: "SANDISK"},
{id: 503, name: "MICRON"},
{id: 504, name: "BITCOIN-MtGOX"},
{id: 505, name: "ATHENS "},
{id: 506, name: "former GALATASARAY"},
{id: 507, name: "BIST 100"},
{id: 508, name: "COPPER-NOV16"},
{id: 509, name: "former Al AHLIA INSUR"},
{id: 510, name: "SAUDI INDUSTRIAL"},
{id: 511, name: "BitCOin/USD"},
{id: 512, name: "TEST - BitCOIN/EUR"},
{id: 513, name: "BitCOIN/CHF"},
{id: 514, name: "DORTMUND"},
{id: 515, name: "JUVENTUS F.C."},
{id: 516, name: "A.S. ROMA"},
{id: 517, name: "KING DIGITAL (Candy Crash)"},
{id: 518, name: "EURUSD FXCM"},
{id: 519, name: "EUR/USD FX"},
{id: 520, name: "former SANDS CHINA"},
{id: 521, name: "HUTCHISON "},
{id: 522, name: "former GALAXY ENT"},
{id: 523, name: "EURJPYFXCM"},
{id: 524, name: "former EGX 30"},
{id: 525, name: "EGX 30"},
{id: 526, name: "TEVA (US)"},
{id: 527, name: "CHINA PACIFIC INSU'"},
{id: 528, name: "PING AN INSURANCE "},
{id: 529, name: "CHINA SHENHUA"},
{id: 530, name: "former CHINA OILFIELD"},
{id: 531, name: "former S/PUDONG DEV BANK"},
{id: 532, name: "former FANGDA CARBON"},
{id: 533, name: "ZHEJIANG DAILY MEDIA"},
{id: 534, name: "MIDEA GROUP"},
{id: 535, name: "former FAWCAR"},
{id: 536, name: "former SZAP"},
{id: 537, name: "ZTE"},
{id: 538, name: "GREE"},
{id: 539, name: "LETV"},
{id: 540, name: "former WULIANGYE "},
{id: 541, name: "former SINOTRANS"},
{id: 542, name: "former COOLPAD GROUP"},
{id: 543, name: "former KINGSOFT CORP"},
{id: 544, name: "NETEASE"},
{id: 545, name: "SINA"},
{id: 546, name: "CTRIP.COM INT'"},
{id: 547, name: "SOHU.COM"},
{id: 548, name: "E-COMR' CHINA (DANG)"},
{id: 549, name: "former QIHOO 360"},
{id: 550, name: "TESLA MOTORS"},
{id: 551, name: "former HANG SENG CHINA ENT'"},
{id: 552, name: "NGAS-JAN17"},
{id: 553, name: "WEIBO"},
{id: 554, name: "USD/NGN"},
{id: 555, name: "former OURPALM CO"},
{id: 556, name: "former ZQgame"},
{id: 557, name: "former ETERNAL ASIA MNG'"},
{id: 558, name: "SHENZHEN TATFOOK"},
{id: 559, name: "former 365NET"},
{id: 560, name: "HUAYI BROS' MEDIA"},
{id: 561, name: "HONGBO CO"},
{id: 562, name: "former AVIT "},
{id: 563, name: "YAOJI PLAYING"},
{id: 564, name: "former SIASUN ROBOT"},
{id: 565, name: "former DESAY BATTERY"},
{id: 566, name: "ROSHOW TEC'"},
{id: 567, name: "former SHANGHAI ACE"},
{id: 568, name: "former CHINA SPORT IND'"},

{id: 569, name: "former CHINA AEROSPACE"},
{id: 570, name: "former XIAMEN OVERSEAS"},
{id: 571, name: "former B-RAY MEDIA"},
{id: 572, name: "former DR PENG MEDIA"},
{id: 573, name: "ORIENTAL PEARL"},
{id: 574, name: "VTB BANK"},
{id: 575, name: "BENFICA"},
{id: 576, name: "LAZIO SPA"},
{id: 577, name: "ALIBABA "},
{id: 578, name: "GENERAL ELECTRIC"},
{id: 579, name: "ALPHA BANK"},
{id: 580, name: "NATL' BANK OF GREECE"},
{id: 581, name: "formerv HELLENIC TELECOMMUNICATIONS"},
{id: 582, name: "PIRAEUS BANK"},
{id: 583, name: "former COCA-COLA HELLENIC"},
{id: 584, name: "USD/RON"},
{id: 585, name: "SAMSUNG (lndn)"},
{id: 586, name: "EURUSDA"},
{id: 587, name: "USD/JPY A "},
{id: 588, name: "GBP/USD A"},
{id: 589, name: "Akron C?"},
{id: 590, name: "New York City C?"},
{id: 591, name: "Sacramento C?"},
{id: 592, name: "Chicago C?"},
{id: 593, name: "San Antonio C?"},
{id: 594, name: "Boston C?"},
{id: 595, name: "Indianapolis C?"},
{id: 596, name: "Nashville C?"},
{id: 597, name: "Austin C?"},
{id: 598, name: "Seattle C?"},
{id: 599, name: "Akron F?"},
{id: 600, name: "New York City F?"},
{id: 601, name: "Sacramento"},
{id: 602, name: "Sacramento F?"},
{id: 603, name: "Chicago F?"},
{id: 604, name: "SanAntonio F?"},
{id: 605, name: "San Antonio - F?"},
{id: 606, name: "Boston F?"},
{id: 607, name: "Indianapolis F?"},
{id: 608, name: "Nashville F?"},
{id: 609, name: "Austin F?"},
{id: 610, name: "Seattle F?"},
{id: 611, name: "KIA Motors Corp"},
{id: 612, name: "H &amp; M"},
{id: 613, name: "EUR/PLN"},
{id: 614, name: "USD/TWD"},
{id: 615, name: "GoPRO"},
{id: 616, name: "SPOT EU INDEX"},
{id: 617, name: "former USD/KZT"},
{id: 618, name: "former USD/KGS"},
{id: 619, name: "TEST ASSET 1"},
{id: 620, name: "TEST ASSET 2"},
{id: 621, name: "FORD MOTOR"},
{id: 622, name: "USD/KRW"},
{id: 623, name: "EUR/KRW"},
{id: 624, name: "USD/AED"},
{id: 625, name: "PERRIGO "},
{id: 626, name: "HEATING OIL-FEB17"},
{id: 627, name: "JOHNSON &amp; JOHNSON"},
{id: 628, name: "MAZDA MOTOR"},
{id: 629, name: "TOSHIBA CORP"},
{id: 630, name: "SUMITOMO MITSUI"},
{id: 631, name: "TOYOTA (US)"},
{id: 632, name: "Manhattan C?"},
{id: 633, name: "Manhattan F?"},
{id: 634, name: "former Manhattan OLD"},
{id: 635, name: "Brooklyn C?"},
{id: 636, name: "Brooklyn F?"},
{id: 637, name: "Bronx C?"},
{id: 638, name: "Bronx F?"},
{id: 639, name: "Staten Island C?"},
{id: 640, name: "Staten Island F?"},
{id: 641, name: "Queens C?"},
{id: 642, name: "Queens F?"},
{id: 643, name: "Newark C?"},
{id: 644, name: "Newark F?"},
{id: 645, name: "Jersey City C?"},
{id: 646, name: "Jersey City F?"},
{id: 647, name: "Akron - F"},
{id: 648, name: "Manhattan - F?"},
{id: 649, name: "CAC 40"},
{id: 650, name: "CAC FUTURE"},
{id: 651, name: "Manhattan - C?"},
{id: 652, name: "Newark - C?"},
{id: 653, name: "Newark - F?"},
{id: 654, name: "Bronx - C?"},
{id: 655, name: "Bronx - F?"},
{id: 656, name: "Syracuse - C?"},
{id: 657, name: "Syracuse - F?"},
{id: 658, name: "Rochester - C?"},
{id: 659, name: "Rochester - F"},
{id: 660, name: "Albany - C?"},
{id: 661, name: "Albany - F?"},
{id: 662, name: "Staten Island - C?"},
{id: 663, name: "Staten Island - F?"},
{id: 664, name: "GBP/USD S"},
{id: 665, name: "Dallas C?"},
{id: 666, name: "Dallas F?"},
{id: 667, name: "Denver C?"},
{id: 668, name: "Denver F?"},
{id: 669, name: "Madison C?"},
{id: 670, name: "Madison F?"},
{id: 671, name: "Phoenix C?"},
{id: 672, name: "Phoenix F?"},
{id: 673, name: "Akron - C?"},
{id: 674, name: "Chicago - C?"},
{id: 675, name: "Chicago - F?"},
{id: 676, name: "NewYorkCity - C?  "},
{id: 677, name: "NewYorkCity - F?"},
{id: 678, name: "Brooklyn - C?"},
{id: 679, name: "Brooklyn - F?"},
{id: 680, name: "Queens - C?"},
{id: 681, name: "Queens - F?"},
{id: 682, name: "Sacramento - C?"},
{id: 683, name: "Boston - C?"},
{id: 684, name: "Boston - F?"},
{id: 685, name: "Nashville - C?"},
{id: 686, name: "Nashville - F?  "},
{id: 687, name: "Austin - C?     "},
{id: 688, name: "Austin - F?"},
{id: 689, name: "SanAntonio - C?"},
{id: 690, name: "Indianapolis - C?"},
{id: 691, name: "Indianapolis - F?"},
{id: 692, name: "Seattle - C?"},
{id: 693, name: "Seattle - F?"},
{id: 694, name: "JerseyCity - C?"},
{id: 695, name: "JerseyCity - F?"},
{id: 696, name: "SOYBEAN-MAR17"},
{id: 697, name: "ORANGE-SEP17"},
{id: 698, name: "PALLADIUM-DEC16"},
{id: 699, name: "RICE-NOV16"},
{id: 700, name: "COTTON-OCT17"},
{id: 701, name: "COCOA-SEP17"},
{id: 702, name: "CISCO"},
{id: 703, name: "former ATHENS F-FEB16"},
{id: 704, name: "TEST ASSET 3"},
{id: 705, name: "BitCoin/CNY"},
{id: 706, name: "TEST ASSET 5"},
{id: 707, name: "WESFARMERS"},
{id: 708, name: "CSL"},
{id: 709, name: "NZX50"},
{id: 710, name: "USD/GEL"},
{id: 711, name: "EUR/GEL"},
{id: 712, name: "OIL-OCT17 (BRENT)"},
{id: 713, name: "USD/CLP"},
{id: 714, name: "PROCTER &amp; GAMBLE"},
{id: 715, name: "EUR/JPY A"},
{id: 716, name: "AUD/USD A"},
{id: 717, name: "GBP/JPY A"},
{id: 718, name: "AUD/USD A"},
{id: 719, name: "SO RETAIL INDEX"},
{id: 720, name: "SO SOCIAL INDEX"},
{id: 721, name: "SO INTERNET INDEX"},
{id: 722, name: "SO E.U CAR INDEX"},
{id: 723, name: "USD/RMB"},
{id: 724, name: "SO E.U BANK INDEX"},
{id: 725, name: "SO U.S FINANCIALS"},
{id: 726, name: "SO TECHNOLOGY INDEX"},
{id: 727, name: "SO COMMODITIES INDEX"},
{id: 728, name: "SO E.U BEAR INDEX"},
{id: 729, name: "SO U.S BEAR INDEX"},
{id: 730, name: "ADIDAS"},
{id: 731, name: "RUSSELL 2000"},
{id: 732, name: "VF CORP"},
{id: 733, name: "UNDER ARMOUR"},
{id: 734, name: "SO U.S SPORT INDEX"},
{id: 735, name: "USD/ARS"},
{id: 736, name: "SPYSIXTEST"},
{id: 737, name: "NIKKEI VS SUMITOMO MITSUI"},
{id: 738, name: "MAZDA VS TOSHIBA"},
{id: 739, name: "NIKKEI 225 VS TOSHIBA"},
{id: 740, name: "UNICREDIT"},
{id: 741, name: "EUR/AMD"},
{id: 742, name: "Adelaide, AU (C?)"},
{id: 743, name: "Adelaide, AU (C?)"},
{id: 744, name: "Brisbane, AU (C?)"},
{id: 745, name: "Melbourne, AU (C?)"},
{id: 746, name: "Perth, AU (C?)"},
{id: 747, name: "Sydney, AU (C?)"},
{id: 748, name: "Adelaide, AU (F?)"},
{id: 749, name: "Brisbane, AU (F?)"},
{id: 750, name: "Melbourne, AU (F?)"},
{id: 751, name: "Perth, AU (F?)"},
{id: 752, name: "Sydney, AU (F?)"},
{id: 753, name: "Calgary, CA (C?)"},
{id: 754, name: "Montreal, CA (C?)"},
{id: 755, name: "Toronto, CA (C?)"},
{id: 756, name: "Vancouver, CA (C?)"},
{id: 757, name: "Calgary, CA (F?)"},
{id: 758, name: "Montreal, CA (F?)"},
{id: 759, name: "Toronto, CA (F?)"},
{id: 760, name: "Vancouver, CA (F?)"},
{id: 761, name: "Auckland, NZ (C?)"},
{id: 762, name: "Auckland, NZ (F?)"},
{id: 763, name: "Haifa, IL (C?)"},
{id: 764, name: "Jerusalem, IL (C?)"},
{id: 765, name: "Tel Aviv, IL (C?)"},
{id: 766, name: "Haifa, IL (F?)"},
{id: 767, name: "Jerusalem, IL (F?)"},
{id: 768, name: "Tel Aviv, IL (F?)"},
{id: 769, name: "Cape Town, ZA (C?)"},
{id: 770, name: "Durban, ZA (C?)"},
{id: 771, name: "BARCLAYS VS LLOYDS BANK"},
{id: 772, name: "Johannesburg, ZA (C?)"},
{id: 773, name: "DAX F VS FTSE F"},
{id: 774, name: "Washington DC, VA (F?)"},
{id: 775, name: "Virginia Beach, VA (F?)"},
{id: 776, name: "St. Louis, MO (F?)"},
{id: 777, name: "VOLKSWAGEN VS DAIMLER"},
{id: 778, name: "Seattle, WA (F?)"},
{id: 779, name: "San Francisco, CA (F?)"},
{id: 780, name: "San Diego, CA (F?)"},
{id: 781, name: "San Antonio, TX (F?)"},
{id: 782, name: "Salt Lake City, UT (F?)"},
{id: 783, name: "Sacramento, CA (F?)"},
{id: 784, name: "Providence, RI (F?)"},
{id: 785, name: "Portland, OR (F?)"},
{id: 786, name: "SIEMENS VS E.ON"},
{id: 787, name: "Pittsburgh, PA (F?)"},
{id: 788, name: "Phoenix, AZ (F?)"},
{id: 789, name: "Philadelphia, PA (F?)"},
{id: 790, name: "Orlando, FL (F?)"},
{id: 791, name: "New York City, NY (F?)"},
{id: 792, name: "Nashville, TN (F?)"},
{id: 793, name: "Minneapolis, MN (F?)"},
{id: 794, name: "Milwaukee, WI (F?)"},
{id: 795, name: "Miami, FL (F?)"},
{id: 796, name: "Memphis, TN (F?)"},
{id: 797, name: "Port Elizabeth, ZA (C?)"},
{id: 798, name: "Los Angeles, CA (F?)"},
{id: 799, name: "Pretoria, ZA (C?)"},
{id: 800, name: "Las Vegas, NV (F?)"},
{id: 801, name: "Kansas City, MO (F?)"},
{id: 802, name: "Cape Town, ZA (F?)"},
{id: 803, name: "Kansas City, KS (F?)"},
{id: 804, name: "Jacksonville, FL (F?)"},
{id: 805, name: "Indianapolis, IN (F?)"},
{id: 806, name: "Durban, ZA (F?)"},
{id: 807, name: "Johannesburg, ZA (F?)"},
{id: 808, name: "Port Elizabeth, ZA (F?)"},
{id: 809, name: "Pretoria, ZA (F?)"},
{id: 810, name: "Birmingham, UK (C?)"},
{id: 811, name: "Glasgow, UK (C?)"},
{id: 812, name: "Leeds, UK (C?)"},
{id: 813, name: "London, UK (C?)"},
{id: 814, name: "Manchester, UK (C?)"},
{id: 815, name: "Birmingham, UK (F?)"},
{id: 816, name: "Glasgow, UK (F?)"},
{id: 817, name: "Leeds, UK (F?)"},
{id: 818, name: "London, UK (F?)"},
{id: 819, name: "Manchester, UK (F?)"},
{id: 820, name: "Atlanta, GA (C?)"},
{id: 821, name: "Baltimore, MD (C?)"},
{id: 822, name: "Charlotte, NC (C?)"},
{id: 823, name: "Cincinnati, OH (C?)"},
{id: 824, name: "Cleveland, OH (C?)"},
{id: 825, name: "Columbus, OH (C?)"},
{id: 826, name: "Dallas, TX (C?)"},
{id: 827, name: "Denver, CO (C?)"},
{id: 828, name: "Detroit, MI (C?)"},
{id: 829, name: "Houston, TX (C?)"},
{id: 830, name: "Atlanta, GA (F?)"},
{id: 831, name: "Baltimore, MD (F?)"},
{id: 832, name: "Charlotte, NC (F?)"},
{id: 833, name: "Cincinnati, OH (F?)"},
{id: 834, name: "Cleveland, OH (F?)"},
{id: 835, name: "Columbus, OH (F?)"},
{id: 836, name: "Dallas, TX (F?)"},
{id: 837, name: "Denver, CO (F?)"},
{id: 838, name: "Detroit, MI (F?)"},
{id: 839, name: "Houston, TX (F?)"},
{id: 840, name: "USD/AMD"},
{id: 841, name: "USD/BGN"},
{id: 842, name: "Cleveland, OH (F?)"},
{id: 843, name: "Columbus, OH (F?)"},
{id: 844, name: "Dallas, TX (F?)"},
{id: 845, name: "Denver, CO (F?)"},
{id: 846, name: "Detroit, MI (F?)"},
{id: 847, name: "Houston, TX (F?)"},
{id: 848, name: "Indianapolis, IN (F?)"},
{id: 849, name: "Jacksonville, FL (F?)"},
{id: 850, name: "Kansas City, KS (F?)"},
{id: 851, name: "Kansas City, MO (F?)"},
{id: 852, name: "Las Vegas, NV (F?)"},
{id: 853, name: "Los Angeles, CA (F?)"},
{id: 854, name: "Memphis, TN (F?)"},
{id: 855, name: "Miami, FL (F?)"},
{id: 856, name: "Milwaukee, WI (F?)"},
{id: 857, name: "Minneapolis, MN (F?)"},
{id: 858, name: "Nashville, TN (F?)"},
{id: 859, name: "New York City, NY (F?)"},
{id: 860, name: "Orlando, FL (F?)"},
{id: 861, name: "Philadelphia, PA (F?)"},
{id: 862, name: "Phoenix, AZ (F?)"},
{id: 863, name: "Pittsburgh, PA (F?)"},
{id: 864, name: "Portland, OR (F?)"},
{id: 865, name: "Providence, RI (F?)"},
{id: 866, name: "Sacramento, CA (F?)"},
{id: 867, name: "Salt Lake City, UT (F?)"},
{id: 868, name: "San Antonio, TX (F?)"},
{id: 869, name: "San Diego, CA (F?)"},
{id: 870, name: "San Francisco, CA (F?)"},
{id: 871, name: "Seattle, WA (F?)"},
{id: 872, name: "St. Louis, MO (F?)"},
{id: 873, name: "Virginia Beach, VA (F?)"},
{id: 874, name: "Washington DC, VA (F?)"},
{id: 875, name: "SPORT DIRECT"},
{id: 876, name: "PUMA"},
{id: 877, name: "SO E.U SPORT INDEX"},
{id: 878, name: "FOOT LOCKER"},
{id: 879, name: "AKAMAI TECHNOLOGIES"},
{id: 880, name: "GoDaddy"},
{id: 881, name: "EUR/BGN"},
{id: 882, name: "QUALCOMM"},
{id: 883, name: "FedEX"},
{id: 884, name: "LUFTHANSA"},
{id: 885, name: "ROYAL DUTCH"},
{id: 886, name: "AIRBUS GROUP"},
{id: 887, name: "former KRAFT FOODS GROUP"},
{id: 888, name: "GOLD A"},
{id: 889, name: "YOOX"},
{id: 890, name: "ANIMA HOLDINGS"},
{id: 891, name: "HONDA MOTOR"},
{id: 892, name: "GBP/INR"},
{id: 893, name: "Plains All American Pipeline"},
{id: 894, name: "AFRICA 40"},
{id: 895, name: "AEX "},
{id: 896, name: "PLUS500"},
{id: 897, name: "VERIZON"},
{id: 898, name: "COSTCO"},
{id: 899, name: "TEST-BitCOIN/GBP"},
{id: 900, name: "AUDI"},
{id: 901, name: "VIPSHOP HOLDINGS LTD"},
{id: 902, name: "YOUKU TUDOU INC"},
{id: 903, name: "JD.COM"},
{id: 904, name: "USD/UGX"},
{id: 905, name: "WELLS FARGO"},
{id: 906, name: "TEST SO1"},
{id: 907, name: "USD/JPY S"},
{id: 908, name: "PANDAUSD/JPY"},
{id: 909, name: "EUR/USD LMAX"},
{id: 910, name: "AUDI AG"},
{id: 911, name: "PANDAGBP/USD"},
{id: 912, name: "3D SYSTEMS"},
{id: 913, name: "BitCOIN/PLN"},
{id: 914, name: "BitCOIN/AUD"},
{id: 915, name: "BitCOIN/JPY"},
{id: 916, name: "PEPSICO"},
{id: 917, name: "USD/KES"},
{id: 918, name: "BitCOIN/ZAR"},
{id: 919, name: "BitCOIN/RUB"},
{id: 920, name: "AUD/USD FUTURE"},
{id: 921, name: "BitCOIN/CAD"},
{id: 922, name: "EUR/JPY FUTURE"},
{id: 923, name: "USD/JPY FUTURE"},
{id: 924, name: "PAYPAL"},
{id: 925, name: "LOCKHEED MARTIN"},
{id: 926, name: "FORD"},
{id: 927, name: "CHINA SHIPBUILDING"},
{id: 928, name: "AIR CHINA"},
{id: 929, name: "FENERBAHCE"},
{id: 930, name: "SAIC MOTOR"},
{id: 931, name: "Shenzhen Kaifa Technology"},
{id: 932, name: "CITIC SECURITIES"},
{id: 933, name: "CHINA SPACESAT"},
{id: 934, name: "Besiktas"},
{id: 935, name: "CHINA SPACESAT"},
{id: 936, name: "AMAZON VS ALIBABA"},
{id: 937, name: "CHINA SHIPBUILDING VS AIR CHINA"},
{id: 938, name: "ALIBABA VS JD.com"},
{id: 940, name: "USD/LKR TEST"},
{id: 942, name: "HOME DEPOT"},
{id: 943, name: "LOWE'S"},
{id: 944, name: "USD/BDT TEST"},
{id: 945, name: "USD/CZK"},
{id: 946, name: "EUR/CNY"},
{id: 947, name: "GBP/CNY"},
{id: 948, name: "AUD/CNY"},
{id: 949, name: "JPY/CNY"},
{id: 950, name: "CAD/CNY"},
{id: 951, name: "CHF/CNY"},
{id: 952, name: "CNY/USD"},
{id: 953, name: "SGX FTSE CHINA A50 INDEX FUTURES"},
{id: 954, name: "COLGATE-PALMOLIVE"},
{id: 955, name: "FIAT CHRYSLER "},
{id: 956, name: "FERRARI"},
{id: 957, name: "USD/COP"},
{id: 958, name: "MORGAN STANLEY"},
{id: 959, name: "EUR/USD 1"},
{id: 960, name: "GBP/AMD"},
{id: 961, name: "RUB/AMD"},
{id: 962, name: "GOLD/AMD"},
{id: 963, name: "SILVER/AMD"},
{id: 964, name: "SYNCHRONY FINANCIAL"},
{id: 965, name: "HARLEY DAVIDSON"},
{id: 966, name: "HARLEY DAVIDSON TEST"},
{id: 967, name: "AMANA"},
{id: 968, name: "SAMBA"},
{id: 969, name: "FMC"},
{id: 970, name: "ALBEMARLE"},
{id: 971, name: "EUR/USD Z"},
{id: 972, name: "USD/JPY Z"},
{id: 973, name: "GOLD FUTURE"},
{id: 974, name: "USD/JPY 1"},
{id: 975, name: "GBP/USD FUTURE"},
{id: 976, name: "GBP/USD Z"},
{id: 977, name: "SILVER Z"},
{id: 978, name: "AUD/USD Z"},
{id: 979, name: "DAX Z"},
{id: 980, name: "ABN AMRO"},
{id: 981, name: "USD/IDR"},
{id: 982, name: "EUR/JPY 1"},
{id: 983, name: "TADAWUL VS TA"},
{id: 984, name: "LEVTST/LEV"},
{id: 985, name: "EUR/USD vs USD/JPY"},
{id: 986, name: "OIL-FEB"},
{id: 987, name: "VISA"},
{id: 988, name: "EUR/USD gain"},
{id: 989, name: "OIL-AUG17 (BRENT)"},
{id: 990, name: "OIL-JUL17 (BRENT)"},
{id: 991, name: "SO2 TEST"},
{id: 992, name: "GOLD gain"},
{id: 993, name: "USD/JPY gain"},
{id: 994, name: "CHEVRON"},
{id: 995, name: "Galatasaray"},
{id: 996, name: "Sydney,AU(C?)"},
{id: 997, name: "Melbourne,AU(C?)"},
{id: 998, name: "Brisbane,AU(C?)"},
{id: 999, name: "Sydney,AU(F?)"},
{id: 1000, name: "Melbourne,AU(F?)  "},
{id: 1001, name: "Brisbane,AU(F?)"},
{id: 1002, name: "OIL (BRENT) FUTURE"},
{id: 1003, name: "Edmonton,AB(C?)"},
{id: 1004, name: "Montreal,QC(C?)"},
{id: 1005, name: "Calgary,AB(C?)"},
{id: 1006, name: "Ottawa,ON(C?)"},
{id: 1007, name: "Toronto,ON(C?)"},
{id: 1008, name: "Aberdeen,UK(C?)"},
{id: 1009, name: "Borough of Bromley,UK(C?)"},
{id: 1010, name: "Borough of Croydon,UK(C?)"},
{id: 1011, name: "Borough of Camden,UK(C?)"},
{id: 1012, name: "Edinburgh,UK(C?)"},
{id: 1013, name: "London,UK(C?)"},
{id: 1014, name: "Birmingham,UK(C?)"},
{id: 1015, name: "Borough of Harrow,UK(C?)"},
{id: 1016, name: "Glasgow,UK(C?)"},
{id: 1017, name: "Leeds,UK(C?)"},
{id: 1018, name: "Manchester,UK(C?)"},
{id: 1019, name: "Barnet,UK(C?)"},
{id: 1020, name: "Cape Town,ZA(C?)"},
{id: 1021, name: "City of Johannesburg,ZA(C?)"},
{id: 1022, name: "Durban,ZA(C?)"},
{id: 1023, name: "New York City,NY(C?)"},
{id: 1024, name: "Los Angeles,CA(C?)"},
{id: 1025, name: "Chicago,IL(C?)"},
{id: 1026, name: "Houston,TX(C?)"},
{id: 1027, name: "Philadelphia,PA(C?)"},
{id: 1028, name: "Popincourt,FR(C?)"},
{id: 1029, name: "Vaugirard,FR(C?)"},
{id: 1030, name: "Butte Montmartre,FR(C?)"},
{id: 1031, name: "Lyon,FR(C?)"},
{id: 1032, name: "Marseille,FR(C?)"},
{id: 1033, name: "Paris,FR(C?)"},
{id: 1034, name: "Louvre,FR(C?)"},
{id: 1035, name: "Gobelins,FR(C?)"},
{id: 1036, name: "Valencia,ES(C?)"},
{id: 1037, name: "Barcelona,ES(C?)"},
{id: 1038, name: "Madrid,ES(C?)"},
{id: 1039, name: "Dunleary,IR(C?)"},
{id: 1040, name: "Cork,IR(C?)"},
{id: 1041, name: "Dublin,IR(C?)"},
{id: 1042, name: "Rome,IT(C?)"},
{id: 1043, name: "Milan,IT(C?)"},
{id: 1044, name: "Naples,IT(C?)"},
{id: 1045, name: "Berlin,DE(C?)"},
{id: 1046, name: "Hamburg,DE(C?)"},
{id: 1047, name: "Munich,DE(C?)"},
{id: 1048, name: "Melbourne,AU(F?)"},
{id: 1049, name: "Edmonton,AB(F?)"},
{id: 1050, name: "Montreal,QC(F?)"},
{id: 1051, name: "Calgary,AB(F?)"},
{id: 1052, name: "Ottawa,ON(F?)"},
{id: 1053, name: "Toronto,ON(F?)"},
{id: 1054, name: "Aberdeen,UK(F?)"},
{id: 1055, name: "Borough of Bromley,UK(F?)"},
{id: 1056, name: "Borough of Croydon,UK(F?)"},
{id: 1057, name: "Borough of Camden,UK(F?)"},
{id: 1058, name: "Edinburgh,UK(F?)"},
{id: 1059, name: "London,UK(F?)"},
{id: 1060, name: "Birmingham,UK(F?)"},
{id: 1061, name: "Borough of Harrow,UK(F?)"},
{id: 1062, name: "Glasgow,UK(F?)"},
{id: 1063, name: "Leeds,UK(F?)"},
{id: 1064, name: "Manchester,UK(F?)"},
{id: 1065, name: "Barnet,UK(F?)"},
{id: 1066, name: "Cape Town,ZA(F?)"},
{id: 1067, name: "City of Johannesburg,ZA(F?)"},
{id: 1068, name: "Durban,ZA(F?)"},
{id: 1069, name: "New York City,NY(F?)"},
{id: 1070, name: "Los Angeles,CA(F?)"},
{id: 1071, name: "Chicago,IL(F?)"},
{id: 1072, name: "Houston,TX(F?)"},
{id: 1073, name: "Philadelphia,PA(F?)"},
{id: 1074, name: "Popincourt,FR(F?)"},
{id: 1075, name: "Vaugirard,FR(F?)"},
{id: 1076, name: "Butte Montmartre,FR(F?)"},
{id: 1077, name: "Lyon,FR(F?)"},
{id: 1078, name: "Marseille,FR(F?)"},
{id: 1079, name: "Paris,FR(F?)"},
{id: 1080, name: "Louvre,FR(F?)"},
{id: 1081, name: "Gobelins,FR(F?)"},
{id: 1082, name: "Valencia,ES(F?)"},
{id: 1083, name: "Barcelona,ES(F?)"},
{id: 1084, name: "Madrid,ES(F?)"},
{id: 1085, name: "Dunleary,IR(F?)"},
{id: 1086, name: "Cork,IR(F?)"},
{id: 1087, name: "Dublin,IR(F?)"},
{id: 1088, name: "Rome,IT(F?)"},
{id: 1089, name: "Milan,IT(F?)"},
{id: 1090, name: "Naples,IT(F?)"},
{id: 1091, name: "Berlin,DE(F?)"},
{id: 1092, name: "Hamburg,DE(F?)"},
{id: 1093, name: "Munich,DE(F?)"},
{id: 1094, name: "EUR/JPY Z"},
{id: 1095, name: "SAMSUNG UK"},
{id: 1096, name: "TEHRAN TEPIX INDEX"},
{id: 1097, name: "USD/MYR"},
{id: 1098, name: "SPY"},
{id: 1099, name: "QQQ"},
{id: 1100, name: "BTCJPY TEST"},
{id: 1101, name: "EURONA NV"},
{id: 1102, name: "FRONTLINE"},
{id: 1103, name: "TSAKOS ENERGY"},
{id: 1104, name: "DHT HOLDINGS TEST"},
{id: 1105, name: "FTSE FUTURE"},
{id: 1106, name: "BP"},
{id: 1107, name: "LLOYDS Bank"},
{id: 1108, name: "Barclays"},
{id: 1109, name: "British American T"},
{id: 1110, name: "Vodafone"},
{id: 1111, name: "HSBC L"},
{id: 1112, name: "Tesco"},
{id: 1113, name: "Rio Tinto"},
{id: 1114, name: "AT&amp;T "},
{id: 1115, name: "DELTA AIR LINES"},
{id: 1116, name: "Whiting Petroleum"},
{id: 1117, name: "SHARP CORP"},
{id: 1118, name: "AMGEN"},
{id: 1119, name: "USD/NGN"},
{id: 1120, name: "GAMESA"},
{id: 1121, name: "REPSOL"},
{id: 1122, name: "CHIPOTLE MEXICAN"},
{id: 1123, name: "INDITEX"},
{id: 1124, name: "GENERALI"},
{id: 1125, name: "IRON-MAR16"},
{id: 1126, name: "Valeant Pharma"},
{id: 1127, name: "FTSE 250"},
{id: 1129, name: "EUR/USD"},
{id: 1130, name: "USD/CNH"},
{id: 1131, name: "BITCOINSS"},
{id: 1132, name: "LIT ETF"},
{id: 1133, name: "USD/JPY LEVNEW"},
{id: 1134, name: "AUD/USD LEVNEW"},
{id: 1135, name: "EUR/JPY LEVNEW"},
{id: 1136, name: "GBP/USD LEVNEW"},
{id: 1137, name: "OIL-MAY16 LEVNEW"},
{id: 1138, name: "GOLD LEVNEW"},
{id: 1139, name: "SOLAR CITY "},
{id: 1140, name: "LITECOIN "},
{id: 1141, name: "Carnival Cruze"},
{id: 1142, name: "EUR/INR TB"},
{id: 1143, name: "WIG20"},
{id: 1144, name: "RIPPLE/EUR"},
{id: 1145, name: "ETHEREUM"},
{id: 1146, name: "BITCOIN "},
{id: 1147, name: "ETH/JPY"},
{id: 1148, name: "LTC/JPY"},
{id: 1149, name: "TEST-1149 - XRP"},
{id: 1150, name: "BTC/EUR"},
{id: 1151, name: "RIPPLE"},
{id: 1152, name: "DOMINION DIAMOND"},
{id: 1153, name: "BTC/USD"},
{id: 1154, name: "XAUUSD_LMAX"},
{id: 1155, name: "GOLD IDATA"},
{id: 1156, name: "MITSUBISHI MOTORS"},
{id: 1157, name: "MAX OIL F"},
{id: 1158, name: "USD/JPY ID"},
{id: 1159, name: "USD/JPY LMAX"},
{id: 1160, name: "USD/JPY LMAX"},
{id: 1161, name: "USD/JPY LMAX"},
{id: 1162, name: "USO - OIL Fund (ETF)"},
{id: 1163, name: "RIPPLE/JPY"},
{id: 1164, name: "Philex Mining Corp."},
{id: 1165, name: "Mokup1"},
{id: 1166, name: "Mokup4"},
{id: 1167, name: "Mokup11"},
{id: 1168, name: "Mokup45"},
{id: 1169, name: "Mokup198"},
{id: 1170, name: "Mokup581"},
{id: 1171, name: "Mokup921"},
{id: 1172, name: "Mokup976"},
{id: 1173, name: "Mokup977"},
{id: 1174, name: "TURKISH AIRLINES"},
{id: 1175, name: "DXD (ETF)"},
{id: 1176, name: "QID (ETF)"},
{id: 1177, name: "SDS (ETF)"},
{id: 1178, name: "SPXU (ETF)"},
{id: 1179, name: "GOLD/ETH"},
{id: 1180, name: "NINTENDO"},
{id: 1181, name: "MAXVOLKSWAGEN"},
{id: 1182, name: "EUR/USD S"},
{id: 1183, name: "DAX"},
{id: 1184, name: "Deutsche Telekom"},
{id: 1185, name: "LUFTHANSA"},
{id: 1186, name: "ALLIANZ SE"},
{id: 1187, name: "BAYER AG"},
{id: 1188, name: "DAIMLER AG"},
{id: 1189, name: "BMW"},
{id: 1190, name: "DEUTSCHE BANK AG"},
{id: 1191, name: "ADIDAS"},
{id: 1192, name: "VOLKSWAGEN"},
{id: 1193, name: "E.On AG"},
{id: 1194, name: "BASF AG"},
{id: 1195, name: "SIEMENS AG"},
{id: 1196, name: "MAXDAX"},
{id: 1197, name: "MAXBMW"},
{id: 1198, name: "HP Inc"},
{id: 1199, name: "NVIDIA"},
{id: 1200, name: "Pack Index"},
{id: 1201, name: "Blue Chip INDEX"},
{id: 1202, name: "ROYAL BANK OF SCOTLAND"},
{id: 1203, name: "S.O OIL"},
{id: 1204, name: "NORTHROP GRUMMAN CORPORATION"},
{id: 1205, name: "GENERAL DYNAMICS CORPORATION "},
{id: 1206, name: "BAE SYSTEMS"},
{id: 1207, name: "TEST ASSET 007"},
{id: 1208, name: "RAYTHEON COMPANY"},
{id: 1209, name: "ALROSA"},
{id: 1210, name: "PKNORLEN"},
{id: 1211, name: "KGHM POLSKA MIEDZ"},
{id: 1212, name: "Powszechny Zaklad Ubezpieczen SA (PZU)"},
{id: 1213, name: "OrangePL (OPL)"},
{id: 1214, name: "ORACLE"},
{id: 1215, name: "SMITH AND WESSON"},
{id: 1216, name: "GBP/PLN"},
{id: 1217, name: "CHF/PLN"},
{id: 1218, name: "TRIP ADVISOR"},
{id: 1219, name: "LENOVO GROUP LIMITED"},
{id: 1220, name: "ZTE CORPORATION"},
{id: 1221, name: " LG ELECTRONICS INC"},
{id: 1222, name: " ASUSTEK COMPUTER INC"},
{id: 1223, name: "MONSANTO COMPANY (MON)"},
{id: 1224, name: "DASH/EUR"},
{id: 1225, name: "ETH/RIPPLE"},
{id: 1226, name: "BTC/GOLD"},
{id: 1227, name: "MAXDAX F-DEC16"},
{id: 1228, name: "TIME WARNER"},
{id: 1229, name: "VXX"},
{id: 1230, name: "OIL BRENT OCT17 - eSignal BU"},
{id: 1231, name: "GOLD/LTC"},
{id: 1232, name: "MERCK &amp; Co., Inc. (MRK)"},
{id: 1233, name: "MAXNASDAQ"},
{id: 1234, name: "MAXAPPLE"},
{id: 1235, name: "MAXFACEBOOK"},
{id: 1236, name: "MAXALPHABET Inc C (Google)"},
{id: 1237, name: "MAXAMAZON"},
{id: 1238, name: "AUD/RUB"},
{id: 1239, name: "NZD/RUB"},
{id: 1240, name: "UNITED CONTINENTAL HOLDINGS Inc"},
{id: 1241, name: "BESIKTAS"},
{id: 1242, name: "BSANTANDER_TEST"},
{id: 1243, name: "BTC/GBP"},
{id: 1244, name: "LTC/BTC"},
{id: 1245, name: "ETH/GBP"},
{id: 1246, name: "ETHEREUM/BITCOIN"},
{id: 1247, name: "GOLD/RIPPLE"},
{id: 1248, name: "TEST-TESCO ESIGNAL"},
{id: 1249, name: "ASX TEST ESIGNAL"},
{id: 1250, name: "YAHOO TEST ESIGNAL"},
{id: 1251, name: "TEST-NASDAQ F ESIGNAL"},
{id: 1252, name: "TEST-NIKKEI 225 ESIGNAL"},
{id: 1253, name: "TEST-ANZ BANK ESIGNAL"},
{id: 1254, name: "BRENT_LMAX_TEST"},
{id: 1255, name: "TEST-1255-BTC/4K"},
{id: 1256, name: "TEST-FTSE F ESIGNAL"},
{id: 1257, name: "TEST-FACEBOOK ESIGNAL"},
{id: 1258, name: "TEST-CAD/CHF ESIGNAL"},
{id: 1259, name: "TEST-OIL(BRENT) MAR17 ESIGNAL"},
{id: 1260, name: "UNITEDHEALTH GROUP INCORPORATED (UNH)"},
{id: 1261, name: "BBVA ESIGNAL"},
{id: 1262, name: "FANUC CORP"},
{id: 1263, name: "GOLD/GBP"},
{id: 1264, name: "TESTASSET12"},
{id: 1265, name: "MOTOROLA SOLUTIONS, Inc. (MSI)"},
{id: 1266, name: "PHILIPS"},
{id: 1267, name: "ATOS"},
{id: 1268, name: "BANCO BRADESCO"},
{id: 1269, name: "BRIDGESTONE"},
{id: 1270, name: "DUPONT"},
{id: 1271, name: "ENI"},
{id: 1272, name: "PANASONIC"},
{id: 1273, name: "UBS "},
{id: 1274, name: "THE PRICELINE GROUP Inc."},
{id: 1275, name: "STAPLES, Inc."},
{id: 1276, name: "BARNES &amp; NOBLE, Inc."},
{id: 1277, name: "OFFICE DEPOT, Inc."},
{id: 1278, name: "BEST BUY CO, Inc."},
{id: 1279, name: "SNAP Inc."},
{id: 1280, name: "HERSHEY'S"},
{id: 1281, name: "GILEAD SCIENCES"},
{id: 1282, name: "CELGENE"},
{id: 1283, name: "VERTEX"},
{id: 1284, name: "Bristol-Myers"},
{id: 1285, name: "HENKEL"},
{id: 1286, name: "MOBILEYE N.V."},
{id: 1287, name: "COMMERZBANK"},
{id: 1288, name: "CONTINENTAL"},
{id: 1289, name: "Capital One Financial Corporation"},
{id: 1290, name: "INSYS Therapeutics"},
{id: 1291, name: "CARA THERAPEUTICS, INC. (CARA)"},
{id: 1292, name: "AbbVie Inc"},
{id: 1293, name: "GW PHARMACEUTICALS "},
{id: 1294, name: "FITBIT Inc"},
{id: 1295, name: "MERCADO LIBRE"},
{id: 1296, name: "BANCO SANTANDER CHILE"},
{id: 1297, name: "LATAM AIRLINES GROUP S.A"},
{id: 1298, name: "SOCIEDAD QUIMICA Y MINERA DE CHILE S.A"},
{id: 1299, name: "CEMEX, S.A.B. DE C.V"},
{id: 1300, name: "S.A.C.I FALABELLA"},
{id: 1301, name: "IPSA SANTIAGO DE CHILE"},
{id: 1302, name: "IPC"},
{id: 1303, name: "VONOVIA"},
{id: 1304, name: "THYSSENKRUPP AG"},
{id: 1305, name: "BEIERSDORF AG"},
{id: 1306, name: "RWE AG ST"},
{id: 1307, name: "PROSIEBENSAT 1AG"},
{id: 1308, name: "DEUTSCHE BOERSE"},
{id: 1309, name: "MUNICH Re"},
{id: 1310, name: "MERCK KGAA"},
{id: 1311, name: "DEUTSCHE POST AG"},
{id: 1312, name: "LINDE AG"},
{id: 1313, name: "FRESENIUS SE"},
{id: 1314, name: "INFINEON AG"},
{id: 1315, name: "HEIDELBERGCEMENT"},
{id: 1316, name: "FRESENIUS ST"},
{id: 1317, name: "GEELY AUTO"},
{id: 1318, name: "ADVANCED MICRO DEVICES, INC"},
{id: 1319, name: "BTC/RIPPLE"},
{id: 1320, name: "DASH"},
{id: 1321, name: "MOLECULIN BIOTECH, INC"},
{id: 1322, name: "BTC/DASH"},
{id: 1323, name: "BTC/ETH"},
{id: 1324, name: "BITCOIN/LITECOIN"},
{id: 1325, name: "BTC/LTC"},
{id: 1326, name: "ETH/EUR"},
{id: 1327, name: "ETH/LTC"},
{id: 1328, name: "BTC/JPY"},
{id: 1329, name: "WIX"},
{id: 1330, name: "PLAY COMMUNICATIONS"},
{id: 1331, name: "LTC/EUR"},
{id: 1332, name: "EEM (ETF)"},
{id: 1333, name: "XLF Financial SPDR(ETF)"},
{id: 1334, name: "IWM Russel2000 (ETF)"},
{id: 1335, name: "UGAZ Natural Gas LongX3 (ETF)"},
{id: 1336, name: "EFA MSCI EAFE (ETF)"},
{id: 1337, name: "UWT CrudeOil LongX3 (ETN)"},
{id: 1338, name: "UVXY Ultra VIX Short-Term (ETF)"},
{id: 1339, name: "XLE Energy SPDR (ETF)"},
{id: 1340, name: "XLP Consumer Staples (ETF)"},
{id: 1341, name: "XOP S&amp;P Oil &amp; Gas Exploration &amp; Production (E"},
{id: 1342, name: "JNUG Gold Miners BullX3 (ETF)"},
{id: 1343, name: "FXI China Large-Cap (ETF)"},
{id: 1344, name: "UCO Ultra Bloomberg Crude Oil"},
{id: 1345, name: "XLU The Utilities SPDR (ETF)"},
{id: 1346, name: "XLK The Technology SPDR (ETF)"},
{id: 1347, name: "XLV Health CaETF)"},
{id: 1348, name: "XLI Industrial Sector (ETF)"},
{id: 1349, name: "XLB  Materials Sector (ETF)"},
{id: 1350, name: "NXT/USD"},
{id: 1351, name: "SYNCHRONY FINANCIAL"},
{id: 1355, name: "LTC/RIPPLE"},
{id: 1356, name: "DASH/RIPPLE"}
]
